// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU4-cCrSeYhuF6rLstQn-dRTxD7jnJwh4',
    appId: '1:143703074328:web:bd8ba6201fb377da5f456d',
    messagingSenderId: '143703074328',
    projectId: 'lab3-5edca',
    authDomain: 'lab3-5edca.firebaseapp.com',
    storageBucket: 'lab3-5edca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXk8VQaLUW4seeoxn18aVPX_4TO8FoCLw',
    appId: '1:143703074328:android:07e87141289c0cfe5f456d',
    messagingSenderId: '143703074328',
    projectId: 'lab3-5edca',
    storageBucket: 'lab3-5edca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiLGWSig5KPKNVhtLivZNTjhITJ_ZGYSc',
    appId: '1:143703074328:ios:54578001a1edd67d5f456d',
    messagingSenderId: '143703074328',
    projectId: 'lab3-5edca',
    storageBucket: 'lab3-5edca.appspot.com',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiLGWSig5KPKNVhtLivZNTjhITJ_ZGYSc',
    appId: '1:143703074328:ios:f200d42687a893c55f456d',
    messagingSenderId: '143703074328',
    projectId: 'lab3-5edca',
    storageBucket: 'lab3-5edca.appspot.com',
    iosBundleId: 'com.example.lab3.RunnerTests',
  );
}
